import "./globals.css";

export const metadata = {
  title: "Movie App with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
