import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@components/Header";

export const metadata = {
  title: "Movie App with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
